/**
 * Auto-generated by scripts/build-frontend.sh
 * Generated from 4 YAML config(s)
 * DO NOT EDIT — modify configs/*.yaml and rebuild instead.
 */
import { TrackerConfig } from "./types";

const config0: TrackerConfig = {
    "name": "Amplitude",
    "description": "Amplitude analytics event tracking",
    "matchers": [
        {
            "id": "amplitude_batch",
            "label": "Batch",
            "color": "#1c1c76",
            "host": "api2.amplitude.com",
            "path_pattern": "/2/httpapi"
        },
        {
            "id": "amplitude_identify",
            "label": "Identify",
            "color": "#5c5cf0",
            "host": "api2.amplitude.com",
            "path_pattern": "/identify"
        }
    ],
    "extractors": [
        {
            "source": "request.header",
            "field": "content-type",
            "display_name": "Content-Type"
        }
    ],
    "display": {
        "type": "event_table",
        "columns": [
            {
                "field": "matcher_label",
                "label": "Event",
                "type": "badge"
            },
            {
                "field": "timestamp",
                "label": "Time",
                "type": "timestamp"
            },
            {
                "field": "method",
                "label": "Method",
                "type": "text"
            },
            {
                "field": "Content-Type",
                "label": "Content-Type",
                "type": "text"
            },
            {
                "field": "status_code",
                "label": "Status",
                "type": "status_code"
            }
        ]
    }
};

const config1: TrackerConfig = {
    "name": "Firebase Analytics",
    "description": "Google Firebase Analytics event tracking",
    "matchers": [
        {
            "id": "firebase_batch",
            "label": "Batch Upload",
            "color": "#ea4335",
            "host": "app-measurement.com",
            "path_pattern": "/a"
        },
        {
            "id": "firebase_config",
            "label": "Remote Config",
            "color": "#4285f4",
            "host": "firebaseremoteconfig.googleapis.com",
            "path_pattern": "/v1/projects/"
        }
    ],
    "extractors": [
        {
            "source": "request.header",
            "field": "x-firebase-client",
            "display_name": "Firebase Client"
        }
    ],
    "display": {
        "type": "event_table",
        "columns": [
            {
                "field": "matcher_label",
                "label": "Event",
                "type": "badge"
            },
            {
                "field": "timestamp",
                "label": "Time",
                "type": "timestamp"
            },
            {
                "field": "method",
                "label": "Method",
                "type": "text"
            },
            {
                "field": "path",
                "label": "Path",
                "type": "text"
            },
            {
                "field": "status_code",
                "label": "Status",
                "type": "status_code"
            }
        ]
    }
};

const config2: TrackerConfig = {
    "name": "Kidsnote Ads",
    "description": "Kidsnote ad tracking (request/impression/click)",
    "matchers": [
        {
            "id": "ad_request",
            "label": "Ad Request",
            "color": "#8b5cf6",
            "host": "ads-api-kcsandbox-01.kidsnote.com",
            "path_pattern": "/req(\\?|$)"
        },
        {
            "id": "ad_impression",
            "label": "Impression",
            "color": "#3b82f6",
            "host": "ads-api-kcsandbox-01.kidsnote.com",
            "path_pattern": "/imp(\\?|$)"
        },
        {
            "id": "ad_click",
            "label": "Click",
            "color": "#10b981",
            "host": "ads-api-kcsandbox-01.kidsnote.com",
            "path_pattern": "/click(\\?|$)"
        }
    ],
    "extractors": [
        {
            "source": "request.query",
            "field": "adsid",
            "display_name": "Ad ID",
            "primary_key": true
        }
    ],
    "display": {
        "type": "event_table",
        "columns": [
            {
                "field": "Ad ID",
                "label": "Ad ID",
                "type": "code"
            },
            {
                "field": "matcher_label",
                "label": "Event",
                "type": "badge"
            },
            {
                "field": "timestamp",
                "label": "Time",
                "type": "timestamp"
            },
            {
                "field": "status_code",
                "label": "Status",
                "type": "status_code"
            }
        ]
    }
};

const config3: TrackerConfig = {
    "name": "Tiara Analytics",
    "description": "Kakao Tiara analytics event tracking",
    "matchers": [
        {
            "id": "tiara_track",
            "label": "Tiara Event",
            "color": "#f59e0b",
            "host": "stat.tiara.daum.net",
            "path_pattern": ".*"
        }
    ],
    "extractors": [],
    "display": {
        "type": "event_table",
        "columns": [
            {
                "field": "matcher_label",
                "label": "Event",
                "type": "badge"
            },
            {
                "field": "timestamp",
                "label": "Time",
                "type": "timestamp"
            },
            {
                "field": "method",
                "label": "Method",
                "type": "text"
            },
            {
                "field": "path",
                "label": "Path",
                "type": "text"
            },
            {
                "field": "status_code",
                "label": "Status",
                "type": "status_code"
            }
        ]
    }
};

export const trackerConfigs: TrackerConfig[] = [config0, config1, config2, config3];
